package com.terraguard.quakexit.subscription.model;

public final class SubscriptionEnums {
    private SubscriptionEnums() {}

    public enum PlanCode { CLOUD_ESSENTIAL, CLOUD_PLUS, CLOUD_BUILDING, CLOUD_ENTERPRISE }
    public enum BillingPeriod { MONTHLY, ANNUAL }
    public enum SubscriptionStatus { ACTIVE, TRIAL, PENDING_PAYMENT, EXPIRED, CANCELLED, PAST_DUE }
    public enum PaymentStatus { PENDING, APPROVED, REJECTED }
    public enum CustomerType { PERSON, COMPANY }
    public enum ScopeType { USER, PROPERTY, BUILDING, COMPANY }
    public enum FeatureCode {
        DASHBOARD, DIGITAL_TWIN, DEVICE_STATUS, DEVICE_CONTROL_BASIC, PROPERTY_CONFIGURATION,
        MANUAL_SIMULATIONS, PUSH_SMS_ALERTS, EMERGENCY_CONTACTS_5, LOW_BATTERY_ALERTS,
        OFFLINE_DEVICE_ALERTS, EMAIL_SUPPORT, NOTIFICATION_HISTORY, EARTHQUAKE_REPORTS,
        SIMULATION_REPORTS, DEVICE_REPORTS, FALSE_ALARM_REPORTS, FALSE_ALARMS,
        AUDIT, BUILDING_MANAGEMENT, RESIDENT_MANAGEMENT, BULK_DEVICE_REGISTRATION,
        COMMON_AREA_ALARMS, COMMON_AREA_SIMULATIONS, MAINTENANCE, MULTI_BUILDING,
        UNLIMITED_ADMINISTRATORS, EXTERNAL_API, IOT_INTEGRATIONS, HISTORICAL_ANALYTICS,
        ADVANCED_REPORTS, PRIORITY_SUPPORT
    }
}