CREATE TABLE IF NOT EXISTS subscriptions (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    subscriber_id BIGINT NOT NULL,
    plan_code VARCHAR(30) NOT NULL,
    billing_period VARCHAR(20) NOT NULL,
    status VARCHAR(20) NOT NULL,
    scope_type VARCHAR(20) NOT NULL,
    scope_id BIGINT NULL,
    first_year_included BIT NOT NULL,
    starts_at TIMESTAMP(6) NOT NULL,
    expires_at TIMESTAMP(6) NOT NULL,
    cancelled_at TIMESTAMP(6) NULL,
    PRIMARY KEY (id),
    INDEX idx_subscription_user_status (subscriber_id, status),
    CONSTRAINT fk_subscription_user FOREIGN KEY (subscriber_id) REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS subscription_orders (
    id BIGINT NOT NULL AUTO_INCREMENT,
    created_at TIMESTAMP(6) NOT NULL,
    updated_at TIMESTAMP(6) NOT NULL,
    order_code VARCHAR(50) NOT NULL,
    subscription_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    amount DECIMAL(12,2) NULL,
    currency VARCHAR(3) NOT NULL,
    billing_period VARCHAR(20) NOT NULL,
    customer_type VARCHAR(20) NOT NULL,
    customer_name VARCHAR(160) NULL,
    document_type VARCHAR(20) NULL,
    document_number VARCHAR(30) NULL,
    customer_email VARCHAR(180) NOT NULL,
    phone_number VARCHAR(20) NULL,
    address VARCHAR(240) NULL,
    city VARCHAR(100) NULL,
    country VARCHAR(2) NULL,
    company_name VARCHAR(180) NULL,
    tax_id VARCHAR(30) NULL,
    building_id BIGINT NULL,
    department_count INT NULL,
    include_hardware BIT NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_subscription_order_code (order_code),
    INDEX idx_subscription_order_subscription (subscription_id),
    CONSTRAINT fk_subscription_order_subscription FOREIGN KEY (subscription_id) REFERENCES subscriptions(id)
);